# Generated by Django 3.1.7 on 2021-03-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='covid_interface.country')),
                ('response_code', models.IntegerField()),
                ('derived_data', models.JSONField()),
                ('raw_data', models.JSONField()),
                ('update_date', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
